mongo_example_homepage:
    pattern:  /
    defaults: { _controller: MongoExampleBundle:Default:index }

mongo_example_content:
    pattern:  /{id}/
    defaults: { _controller: MongoExampleBundle:Default:content }