parameters:
#    mongo_example.example.class: Mongo\ExampleBundle\Example

services:
#    mongo_example.example:
#        class: %mongo_example.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine_mongodb.odm.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
              - [ setAnnotationReader, [ @annotation_reader ] ]